# Generated by Django 5.0.4 on 2024-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('bf_image', models.ImageField(upload_to='home/')),
                ('bac_image', models.ImageField(upload_to='home/')),
                ('numberof_home', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.IntegerField()),
                ('your_contact', models.IntegerField()),
            ],
        ),
    ]
