# Generated by Django 5.0.4 on 2024-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='phone_owner',
            field=models.IntegerField(default=0),
        ),
    ]
